variables:
  DOCKER_REGISTRY: 095750129829.dkr.ecr.me-south-1.amazonaws.com
  APP_NAME: aca-frontend
.kubectl-config: &kubectl-config
  - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_EKS}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_EKS}
  - export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
  - aws eks update-kubeconfig --name=ezpick-prod --region=${AWS_DEFAULT_REGION}
  # - aws eks update-kubeconfig --name ezpick-prod  --region me-south-1
  - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
  # - aws ecr get-login-password | docker login --username AWS --password-stdin 095750129829.dkr.ecr.me-south-1.amazonaws.com
image: armughanmb/gitlab-k8-essentials
services:
    - docker:dind
stages:
  - build_docker_image
  - update_helm_chart
  - deploy_helm_to_kubernetes

Docker Build Dev:
  stage: build_docker_image
  before_script:
    - *kubectl-config
  script:
    - docker build -t $DOCKER_REGISTRY/$APP_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA .
    - docker push $DOCKER_REGISTRY/$APP_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  only:
    - prod


Update HELM chart:
  stage: update_helm_chart
  before_script:
    - *kubectl-config
    - git config --global user.email "abdul.ghafoor@whetstonesz.com"
    - git config --global user.name "mabdulghafoormusa"
  script:
    - git clone https://${GIT_USER}:${GIT_TOKEN}@gitlab.com/abdulghafoormusa/aca-frontend-chart.git
    - cd aca-frontend-chart
    # - git checkout dev
    - sed -i "s|tag:.*|tag:\ $CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA|g" ./app1/values.yaml
    - git add .
    - git commit -m "docker image tag updated to $CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    - git push origin prod
  only:
    - prod

Deploy services on EKS Dev :
  stage: deploy_helm_to_kubernetes
  before_script:
    - *kubectl-config
  script:
    - git clone https://${GIT_USER}:${GIT_TOKEN}@gitlab.com/abdulghafoormusa/aca-frontend-chart.git
    - cd aca-frontend-chart
    - ls -la
    - export DEPLOY=$(helm  lint app1/ -f app1/values.yaml | grep Error | wc -l) && pwd && ls
    # - ls /builds/ezpick/ezpick-backend/ezpick-backend-chart
    - echo "deploy value is ${DEPLOY}"
    - > 
        if [ "${DEPLOY}" -eq 0 ];  
        then helm upgrade --install aca-frontend app1/ -f app1/values.yaml --create-namespace --namespace aca-prod --set image.tag=prod-$CI_COMMIT_SHORT_SHA; 
        else echo "deployment failed" && exit 1; 
        fi;

    # - > 
    #     if [ "${DEPLOY}" -eq 0 ];  
    #     then helm install testing app1/ -f app1/values.yaml --create-namespace --namespace demo --set image.tag=dev-$CI_COMMIT_SHORT_SHA; 
    #     else echo "deployment failed" && exit 5; 
    #     fi;
    # - kubectl rollout status deployment backend-my-app-1 --namespace aca-prod;
  only:
    - prod