name: Reusable Github Actions - Demo

run-name: Github Reusable Workflow

on:
  workflow_call:

jobs:
  called-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v2

      - name: Print the git version
        run: |
          git --version
      - name: Clone the Github Repository
        run: |
         git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/aghafoorhfd/reactjsag.git
         ls reactjsag
    

         
