name: Reusable Workflow

on:
  workflow_call:
    inputs:
      input1:
        required: true
        type: string
    outputs:
      output1:
        value: string 
       
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: set_output
        run: echo "::set-output name=output1::value1"
