on:
  push:
    branches:
      - main

jobs:
  call_reusable_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Call Reusable Workflow
        uses: ./.github/workflows/action.yml
        with:
          input1: ${{ secrets.INPUT_VALUE }}
